### ISSUE TITLE
Test + docs: dataset/loader/interface

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#122]
# Issue description

Tests, docs, lint request for the file interface.py.

- class DataLoader
    - init, moving_image_shape, fixed image shape, num samples, get_dataset, get_Dataset and preprocess, close
- class AbstractPairedDataLoader
    - init, moving_image_shape, fixed image shape, num samples
- class AbstractUnpairedDataLoader
    - init, moving images shape, fixed image shape, numsamples
- class GeneratorDataLoader
    - init, get dataset, data generator, sample index generator, validate images and labels, sample image label
- class COcatenatedDataLoader
    - init, movingimageshape, fixed image shape, num samples, get dataset, close
- class FileLoader
    - init, get data, get data ids, get num images, set group structure, get num groups, get num images per group, close

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests for inputs, outputs, asserts for all methods and classes

**Comment by mathpluscode** [comment]
@NMontanaBrown can we write some guidelines that how these interface classes should be tested?

- for the not implemented functions, we can simply check calling them will raise errors.
- for the implemented functions, we might have to init some class instances in order to test it

maybe we can ask the team to first cover those not implemented functions, and add TODOs for others.

**Comment by mathpluscode** [comment]
Hi @RemiDelaunay , do you need some help here? It has been a while and some changes have had place in interface, I'm wondering if it will impact your branch

**Comment by RemiDelaunay** [comment]
Hi @mathpluscode. Sorry I was busy with other things and I'm on annual leave this week. I am almost done (considering the recent changes) and I will pull everything when I come back.

**Comment by mathpluscode** [comment]
In #257 I adapted existing tests into pytest style, the rest will wait until @RemiDelaunay 's back ;)

**Comment by mathpluscode** [comment]
Hi @RemiDelaunay, the fix of multiple directories has been merged to the master branch, and when you are back, you can continue the test covering for `interface.py`. This is the last big piece of the code to do and with this will can achieve >95% coverage!

Btw, in your previous code, I found that you were using `unittest` package, and unfortunately, this is not the one we are using, therefore I've prepared a small guide on the testing with pytest: https://deepregnet.github.io/DeepReg/#/CONTRIBUTING?id=unit-tests Hope it can help you a bit ;)

**Comment by RemiDelaunay** [comment]
Hi @mathpluscode , I have updated my version of test_interface.py to cover the recent changes and created a pull request for it. Sorry for using unittest, I thought it was ok to use because I have seen it elsewhere (e.g., [test_config_parser.py](https://github.com/DeepRegNet/DeepReg/blob/d86771e38b8270e0473d7660946ade4e282e8d78/test/unit/test_config_parser.py)).

**Comment by mathpluscode** [comment]
@RemiDelaunay ooops good catch, git blame shows that it's my code ;) will fix this
