### ISSUE TITLE
Docs: All links on wiki tutorial index are broken

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#169]
# Issue description

Going through the wiki, I tried to access [the linked tutorial](https://github.com/ucl-candi/DeepReg/blob/master/tutorials/registration.md) but it lead me to 404. Any pointers?

## Type of Issue

Please delete options that are not relevant.

- [x] Bug report
- [x] Documentation update

**Comment by NMontanaBrown** [comment]
Actually, all the links on the [wiki page](https://github.com/ucl-candi/DeepReg/wiki/Tutorial-Index) are broken?

**Comment by mathpluscode** [comment]
@NMontanaBrown these are due to the changes of markdown files. I think we should clean the wiki a bit once we set up the deepreg.net properly after moving repo.

I personally suggest put everything in markdown files so all should be on the website. Information in two different places are not very consistent. And... github wiki is not that beautiful lol

**Comment by YipengHu** [comment]
> @NMontanaBrown these are due to the changes of markdown files. I think we should clean the wiki a bit once we set up the deepreg.net properly after moving repo.
> 
> I personally suggest put everything in markdown files so all should be on the website. Information in two different places are not very consistent. And... github wiki is not that beautiful lol

I will clean this up after migration - the wiki can be used to host devmeeting record - agree on all docs should be in /docs

**Comment by mathpluscode** [comment]
meeting notes...? i think wiki if public? well unless meeting nodes are ok to be public

**Comment by YipengHu** [comment]
i think for an OS project, everything should be public unless there is a good reason not to.
