### ISSUE TITLE
Prediction output

### ISSUE THREAD

**Issue by acasamitjana** [DeepRegNet/DeepReg#214]
# Issue description

## Type of Issue
Bug when saving the output: it does not create separate folders for different pairs of images.
New feature: save the output in the same format as the input. 

Please delete options that are not relevant.

- [X] Bug report
- [X] New feature request
- [ ] Documentation update
- [ ] Test request
- [ ] Linting request

#### Additional details / screenshot

I'd suggest to create a different folder for each pair of images where you could save the image and all the sampled labels in the same format of the input (you already specify the format in the input, so you could create, e.g., a NiftyFileWriter and H5FileWriter classes in the same way you have the respective file loaders). Moreover you could save it as png if required by a flag in the config file. E.g:

- 10_15:
    - warped_image.nii
    - warped_label_0.nii
    - warped_label_1.nii
    - images (dir, optional)
    - label_0 (dir, optional)
    - label_1 (dir, optional)

-18_23:
    -warped_image.nii
    - ...
...

**Comment by mathpluscode** [comment]
what do you mean "it does not create separate folders for different pairs of images", in unpaired or grouped? 

I thought the code is working like, for each pair of images, you will have indices to identify them,
- if they are labeled, then the last index is for label, others are for identifying this pair
- if they are unlabeled, then the whole indices are for identifying the pair

When saving outputs, we will use the indices to create folders, `image_xxx` or `image_xxx_label_yyy`.

So I don't understand why you say it does not create separate folder for different pairs? any screenshot to help me understand it?

Otherwise, yes, i think your proposition on the output structure is better, will change to this.

**Comment by acasamitjana** [comment]
<img width="710" alt="prediction" src="https://user-images.githubusercontent.com/19728301/88375719-61f10880-cd9c-11ea-86f6-9cf4efad1cb6.png">

Find a picture here. When it is labeled, the "image pair" index is not used, so it will create only L folders (L = number of labels), but it will overwrite the results on each predict() iteration.

**Comment by acasamitjana** [comment]
<img width="529" alt="prediction" src="https://user-images.githubusercontent.com/19728301/88376005-e9d71280-cd9c-11ea-9cc6-f7059bdf1bf2.png">

Find a picture here. When it is labeled, the "image pair" index is not used, so it will create only L folders (L = number of labels), and it will overwrite the results on each predict() iteration. Does that make sense?

**Comment by NMontanaBrown** [comment]
As a heads up, the MICCAI Edu Challenge submission relies on the old version of predict, so if we are to change this functionality the notebook must be edited too and checked that it still works such that it won't break once this is merged to master. Issue #196 .

**Comment by mathpluscode** [comment]
oh @acasamitjana sorry, it's a bug indeed, i wanted
```
if labeled:
    image_dir = os.path.join(image_dir, xxxx)
```
