### ISSUE TITLE
Dependency on cloned repo

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#397]
## Subject of the feature

Currently the Quick Start is dependent on test data, config and absolute path, while demos are dependent on absolute path. Therefore, the PyPI installed DeepReg needs to manually download test data and config to run Quick Start, and demos need change path manually.
It would be ideal to remove this dependency.

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

Yes

**Comment by zacbaum** [comment]
To make sure we are solving the right problem...

The issue is that we want to (somehow) include `/config`, `/data` (and maybe `/demos`) in the release, right? So that users can directly do the Quick Start tests and run demos without (many) additional steps.

Right now, when you `pip install deepreg`, these folders and their contained files (if we include them in the release) are buried away in your `conda` environment - making them non-trivial to access and use because of the paths being absolute.

Currently, if you pip install, and run any of the Quick Start tests from within the cloned repo (with your env's version of deepreg created from `pip install deepreg`, not `pip install -e .`), things work as expected.

We have a few (two that I can think of) options for how to do this:

1. Include the folders and their contained files in the release, have an additional entry point which users can run from the command line to copy those files to either a) the current directory or b) a user-specified directory;
2. Don't include the folders and their contained files in the release, have an additional entry point which users can run from the command line to download those files to either a) the current directory or b) a user-specified directory

What do we prefer? The first may be simpler (doesn't require downloading anything, just copying files around on the user's machine) but requires messing around with the release packaging to ensure that all these additional files are included.

The second is probably more involved to code (involves downloading files, etc.), but doesn't require additional bulk in the release from the `/data` or `/demos` folder, and therefore would only require the user does this one-liner ahead of doing anything in Quick Start (which would also be required in option 1!).

What do people think?

@YipengHu @mathpluscode @NMontanaBrown @ebonmati @agrimwood

**Comment by zacbaum** [comment]
NiftyNet used this to download from their model zoo; see here: https://github.com/NifTK/NiftyNet/blob/dev/niftynet/utilities/download.py

**Comment by NMontanaBrown** [comment]
I personally prefer 2.

> To make sure we are solving the right problem...
> 
> The issue is that we want to (somehow) include `/config`, `/data` (and maybe `/demos`) in the release, right? So that users can directly do the Quick Start tests and run demos without (many) additional steps.
> 
> Right now, when you `pip install deepreg`, these folders and their contained files (if we include them in the release) are buried away in your `conda` environment - making them non-trivial to access and use because of the paths being absolute.
> 
> Currently, if you pip install, and run any of the Quick Start tests from within the cloned repo (with your env's version of deepreg created from `pip install deepreg`, not `pip install -e .`), things work as expected.
> 
> We have a few (two that I can think of) options for how to do this:
> 
> 1. Include the folders and their contained files in the release, have an additional entry point which users can run from the command line to copy those files to either a) the current directory or b) a user-specified directory;
> 2. Don't include the folders and their contained files in the release, have an additional entry point which users can run from the command line to download those files to either a) the current directory or b) a user-specified directory
> 
> What do we prefer? The first may be simpler (doesn't require downloading anything, just copying files around on the user's machine) but requires messing around with the release packaging to ensure that all these additional files are included.
> 
> The second is probably more involved to code (involves downloading files, etc.), but doesn't require additional bulk in the release from the `/data` or `/demos` folder, and therefore would only require the user does this one-liner ahead of doing anything in Quick Start (which would also be required in option 1!).
> 
> What do people think?
> 
> For reference... `/config` is 8KB, `/demos` is 132KB, and `/data` is 84MB - Quite a large addition to the package if we go the include with release route.
> 
> @YipengHu @mathpluscode @NMontanaBrown @ebonmati @agrimwood
