### ISSUE TITLE
Reformat Demo's for a Visually Consistent Output

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#474]
## Subject of the documentation

What are you trying to do and which part of the code is hard to understand or incorrect
or missing? Please provide a link to the readthedocs page and code if available.

Our docs have visually inconsistent outputs. We now have a tool to produce videos/gifs. Make the demos have equal output by adding the gif tool to the demos.

If the documentation request is approved, would you be willing to submit a PR? _(Help
can be provided if you need assistance submitting a PR)_

No

**Comment by s-sd** [comment]
@mathpluscode, is the vis tool being removed? I was looking at ffmpeg and I think the vis tool has some additional functionality like being able to make gifs that show warping, tiled gifs and a plot of only a few slices (like in the edu challenge notebook). Also the vis tool would make it easier to make demo outputs consistent just using the tool rather than adding new code for the visualisations. But if you think that there is a large overlap with ffmpeg then we can remove. Let me know either way and I'll get started with this ticket.

**Comment by mathpluscode** [comment]
no? @s-sd 

I just personally find ffmpeg enough for me :) and finding the vis tool a bit hard to understand what's going on, maybe a doc with some images to show the results can be helpful? no intention to remove it if it has extra functionalities ^^

**Comment by s-sd** [comment]
Thanks @mathpluscode, I have created a new ticket to update the vis tool documentation and have assigned this to myself (#564) and for now I'll use the vis tool for this ticket as well to make the demo outputs consistent.
