### ISSUE TITLE
2D(US)/3D(CT) Registration 

### ISSUE THREAD

**Issue by pdb1263** [DeepRegNet/DeepReg#486]
## Subject of the feature
2D(US)/3D(CT) Registration 

What are you trying to do and how would you want to do it differently?
Trying to use DeepReg to register 3D-CT to 2D-US in REAL TIME

Is it something you currently you cannot do?
Not sure but documentation explicitly says current implementation (and examples) are 3D-3D only. Still not sure if current implementation will handle 2D-3D "just like that" and how. Also, Paired Prostate Demo takes around ~280 ms/inference on Quadro P1000, which is sub-RT. Could this be improved somehow?

Is this related to an issue/problem?
This is related to research

Has the feature been requested before? If yes, please provide a link to the issue.
Don't know

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_
Probably

**Comment by YipengHu** [comment]
Hi @pdb1263 very good question. In short, DeepReg does not support 2D-to-3D. However, if you are working with 2D tomography such as ultrasound, you might have a chance to replicate the data to, say, of depth of 3, such that it becomes a 3d-to-3d problem. Then the rest will be a research question as if it is actually going to work. Happy to assist if you are keen to try it.

Re speed, this is a more engineering problem depends on your machine and GPU card etc... and if you have your workflow entirely on GPU (otherwise the RAM->GPU time is not trivial). How did you measure the inference?

**Comment by YipengHu** [comment]
@pdb1263 I'm closing this now - do open a new ticket if you would like to follow this up :)
