### ISSUE TITLE
MobileNetv3 for dense prediction

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#678]
## Subject of the feature

Implement mobilenetv3 for potential training/memory efficiency

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

Yes / No

**Comment by YipengHu** [comment]
efficient-net is another option.

**Comment by YipengHu** [comment]
Have a look at this @SicongluUCL - please assign yourself when start.

**Comment by SicongluUCL** [comment]
I can take this task. Thanks.

**Comment by SicongluUCL** [comment]
As we are medical image processing, we need to find 3D NN model for this demand. Maybe we can use some open source codes for 3D-MobileNet or 3D-EfficientNet.
After doing research, I found some resouces:
1. The repository contains 3D variants of EfficientNet models for classification.
https://github.com/ZFTurbo/efficientnet_3D

2. I think I can refer to some models of 3D object detection, because XYZ and intensity from pointclouds are similar in CT-lung
I refer https://github.com/open-mmlab/mmdetection3d (OpenMMLab Sensetime Open Source)

3. If nothing else works, I think I can use 3D convolution to build this model from scratch. For example, I can use some api like: 
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv3D

BTW, I was inspired by NLTK. There are some models that I'm not sure whether I can use:
(1) 3D AutoEncoder
https://github.com/DLTK/DLTK/blob/master/dltk/networks/autoencoder/convolutional_autoencoder.py
(2) 3D Resnet
https://github.com/DLTK/DLTK/blob/master/dltk/networks/regression_classification/resnet.py
(3) 3D FCN
https://github.com/DLTK/DLTK/blob/master/dltk/networks/segmentation/fcn.py

**Comment by YipengHu** [comment]
@SicongluUCL A good start! Thanks.
All three options seem sensible to me. I would start with Opt. 2 here as this is a wider-used code base (which arguably has more chances to be better quality - but this is very much subjective and biased). But does it have an efficient-net or mobile-net and the likes implemented? If not, perhaps a combination of Opts 1 and 2 is the way forward, i.e. use Opt1 as reference and cross-validate with those components implemented in opt 2? 

DLTK is also a good source, but again, i'm not sure the exactly the network we want has been implemented yet. 

Although in PyTorch, a technical reference would be this: https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/nets/efficientnet.py

**Comment by mathpluscode** [comment]
> As we are medical image processing, we need to find 3D NN model for this demand. Maybe we can use some open source codes for 3D-MobileNet or 3D-EfficientNet.
> After doing research, I found some resouces:
> 
> 1. The repository contains 3D variants of EfficientNet models for classification.
>    https://github.com/ZFTurbo/efficientnet_3D
> 2. I think I can refer to some models of 3D object detection, because XYZ and intensity from pointclouds are similar in CT-lung
>    I refer https://github.com/open-mmlab/mmdetection3d (OpenMMLab Sensetime Open Source)
> 3. If nothing else works, I think I can use 3D convolution to build this model from scratch. For example, I can use some api like:
>    https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv3D
> 
> BTW, I was inspired by DLTK. There are some models that I'm not sure whether I can use:
> (1) 3D AutoEncoder
> https://github.com/DLTK/DLTK/blob/master/dltk/networks/autoencoder/convolutional_autoencoder.py
> (2) 3D Resnet
> https://github.com/DLTK/DLTK/blob/master/dltk/networks/regression_classification/resnet.py
> (3) 3D FCN
> https://github.com/DLTK/DLTK/blob/master/dltk/networks/segmentation/fcn.py

@SicongluUCL I agree with @YipengHu, Open-MMLab is a great repo, our registry system is also inspired by it :) nice work
